-- Gradebook column groups.
--
-- Before this migration, "column group" was not a stored concept. The
-- groupedColumns memo in app/course/[course_id]/manage/gradebook/gradebookTable.tsx
-- derived groups on every render by splitting gradebook_columns.slug on "-",
-- special-casing slugs shaped assignment-<type>-*, and then requiring that a
-- group's sort_order values run consecutively. Grouping therefore depended on a
-- naming convention that instructors cannot influence: slugs are immutable
-- (see prevent_slug_update) and assignment-derived slugs are generated.
--
-- This migration makes a group a row.
--
-- Membership model: gradebook_columns.group_id is a nullable FK. Membership is
-- independent of sort_order, so a group's columns are not required to be
-- adjacent. That choice is deliberate and is discussed in the PR writeup; the
-- consequence is that a non-contiguous group is representable, and the renderer
-- resolves it by ordering groups on gradebook_column_groups.sort_order and
-- ordering columns within a group on gradebook_columns.sort_order.
--
-- NULL group_id means "ungrouped", which renders as a standalone column. That is
-- also the stated policy for rows the backfill cannot classify (see below).

-- ---------------------------------------------------------------------------
-- 1. Let a group's (gradebook_id, class_id) pair be validated by the database.
--    gradebook_columns carries both, and the group table has to as well:
--    class_id is what the RLS predicates key on, gradebook_id is the real
--    parent. Referencing both columns of gradebooks makes it impossible for a
--    group to claim a class its gradebook does not belong to.
-- ---------------------------------------------------------------------------

alter table public.gradebooks
  add constraint gradebooks_id_class_id_key unique (id, class_id);

-- ---------------------------------------------------------------------------
-- 2. The group.
-- ---------------------------------------------------------------------------

create table public.gradebook_column_groups (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  class_id bigint not null,
  gradebook_id bigint not null,
  name text not null,
  slug text not null,
  sort_order integer not null,
  description text,

  constraint gradebook_column_groups_pkey primary key (id),

  constraint gradebook_column_groups_gradebook_fkey
    foreign key (gradebook_id, class_id)
    references public.gradebooks (id, class_id)
    on delete cascade,

  -- Referenced by the composite FK from gradebook_columns below, which is what
  -- prevents a column from joining a group in another gradebook.
  constraint gradebook_column_groups_id_gradebook_key unique (id, gradebook_id),

  -- A title is what the user collapses, so two groups in one gradebook may not
  -- share one. This is the constraint that makes the old duplicate-"Quiz" and
  -- duplicate-"Assignment" headers impossible to express.
  constraint gradebook_column_groups_gradebook_name_key unique (gradebook_id, name),
  constraint gradebook_column_groups_gradebook_slug_key unique (gradebook_id, slug),

  -- Deferrable so a reorder can swap two positions inside one transaction
  -- without a collision on an intermediate state.
  constraint gradebook_column_groups_gradebook_sort_order_key
    unique (gradebook_id, sort_order) deferrable initially immediate,

  constraint gradebook_column_groups_name_not_blank check (btrim(name) <> ''),
  constraint gradebook_column_groups_sort_order_nonneg check (sort_order >= 0),
  constraint gradebook_column_groups_slug_format
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

comment on table public.gradebook_column_groups is
  'A named, ordered cluster of gradebook_columns within one gradebook. Replaces the render-time slug-prefix heuristic that previously derived groups in the browser.';
comment on column public.gradebook_column_groups.slug is
  'Stable machine key, unique per gradebook. Safe to persist collapse state against, unlike the old positional group key.';
comment on column public.gradebook_column_groups.sort_order is
  'Left-to-right position of the group. Independent of gradebook_columns.sort_order.';

create index idx_gradebook_column_groups_class_id
  on public.gradebook_column_groups (class_id);
create index idx_gradebook_column_groups_gradebook_id_sort_order
  on public.gradebook_column_groups (gradebook_id, sort_order);

create trigger set_updated_at_on_gradebook_column_groups
  before update on public.gradebook_column_groups
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 3. Membership.
-- ---------------------------------------------------------------------------

alter table public.gradebook_columns
  add column group_id bigint;

comment on column public.gradebook_columns.group_id is
  'Group this column belongs to, or NULL for ungrouped (renders standalone).';

-- Composite FK: a column may only join a group in its own gradebook. With
-- MATCH SIMPLE a NULL group_id skips the check, which is how "ungrouped" stays
-- legal. ON DELETE SET NULL names group_id explicitly so deleting a group
-- ungroups its columns instead of trying to null out gradebook_id.
alter table public.gradebook_columns
  add constraint gradebook_columns_group_fkey
  foreign key (group_id, gradebook_id)
  references public.gradebook_column_groups (id, gradebook_id)
  on delete set null (group_id);

create index idx_gradebook_columns_group_id
  on public.gradebook_columns (group_id);

-- ---------------------------------------------------------------------------
-- 4. RLS. Mirrors gradebook_columns, which is the table whose visibility a
--    group's visibility has to agree with.
--
--    The read policy is deliberately one step stricter than a plain class
--    membership check: a group's name is instructor-authored text, so a student
--    only sees a group that contains at least one column they can already see.
--    Without that, releasing nothing would still leak the title of a group of
--    unreleased instructor-only columns.
-- ---------------------------------------------------------------------------

alter table public.gradebook_column_groups enable row level security;

create policy "instructors CRUD"
on public.gradebook_column_groups
as permissive
for all
to public
using (authorizeforclassinstructor(class_id));

create policy "everyone in class can view"
on public.gradebook_column_groups
as permissive
for select
to public
using (
  exists (
    select 1
    from public.user_privileges up
    where up.user_id = auth.uid()
      and up.class_id = gradebook_column_groups.class_id
  )
  and (
    exists (
      select 1
      from public.user_privileges up2
      where up2.user_id = auth.uid()
        and up2.class_id = gradebook_column_groups.class_id
        and up2.role in ('instructor', 'grader')
    )
    or exists (
      select 1
      from public.gradebook_columns gc
      where gc.group_id = gradebook_column_groups.id
        and (coalesce(gc.instructor_only, false) = false or gc.released = true)
    )
  )
);

grant delete, insert, references, select, trigger, truncate, update
  on table public.gradebook_column_groups to authenticated;
grant delete, insert, references, select, trigger, truncate, update
  on table public.gradebook_column_groups to service_role;

alter publication supabase_realtime add table public.gradebook_column_groups;

-- ---------------------------------------------------------------------------
-- 5. Backfill.
--
-- Runs against every gradebook that already exists. The policy, stated so it can
-- be argued with:
--
--   a. Family key. A column shaped assignment-<type>-<rest> keys on <type>
--      ("asg:lab"); every other column keys on its first slug segment
--      ("pre:quiz"). The two namespaces are kept separate on purpose: under the
--      old rules a two-segment slug like "assignment-final" missed the
--      length >= 3 special case and fell back to the bare prefix "assignment",
--      which then collided with the real assignment family.
--
--   b. No contiguity requirement. The old rule started a new group whenever
--      sort_order skipped a value. Nothing renumbers sort_order on delete, so a
--      deleted column permanently split its family in two. Families are now
--      whole regardless of holes.
--
--   c. Minimum size 2. A family with one member becomes no group at all; the
--      column is left ungrouped and renders standalone. This is the stated
--      policy for rows that cannot be classified, and it matches what users
--      already saw, because the old code filtered groups of one out of the
--      collapse UI while still constructing them.
--
--   d. Title from names, not slugs. A group is titled with the longest common
--      prefix of its members' name values, trimmed to end on a letter. Titles
--      come from text a human wrote, so "ai-usage-log-1"/"ai-usage-log-2" title
--      as "AI Usage Log" rather than "Ai", and "average.hw" can no longer
--      surface a raw slug as a heading. Falls back to the family key when the
--      common prefix is too short to be useful.
--
-- Deliberately NOT done here: grouping columns by shared dependencies. The
-- schema already records that the three *-expectations aggregates are computed
-- from the same twelve skill columns, and grouping on that is tempting. It is
-- also wrong as stated, because midterm-standing has byte-identical
-- dependencies and does not belong with them. That relationship needs its own
-- structure rather than being folded into this one; see part two of the PR.
-- ---------------------------------------------------------------------------

-- Packaged as a function rather than inlined, for three reasons: migrations
-- replay before any seed runs, so a course created after this migration needs
-- the same classification applied; it is idempotent, so the answer to "what
-- happens if this runs twice" is "nothing"; and it gives instructors an
-- "auto-group my columns" entry point to build the CRUD on later.
--
-- SECURITY INVOKER on purpose. It writes through the caller's RLS, so an
-- instructor can only ever reclassify their own class and the null-argument
-- (every gradebook) form is only actually global for the service role.
create or replace function public.backfill_gradebook_column_groups(
  p_gradebook_id bigint default null
)
returns integer
language plpgsql
set search_path = public, pg_temp
as $function$
declare
  v_assigned integer;
begin
with cols as (
  select
    gc.id,
    gc.gradebook_id,
    gc.class_id,
    gc.name,
    gc.sort_order,
    gc.group_id,
    case
      when (string_to_array(gc.slug, '-'))[1] = 'assignment'
           and array_length(string_to_array(gc.slug, '-'), 1) >= 3
        then 'asg:' || (string_to_array(gc.slug, '-'))[2]
      else 'pre:' || (string_to_array(gc.slug, '-'))[1]
    end as group_key
  from public.gradebook_columns gc
  where p_gradebook_id is null or gc.gradebook_id = p_gradebook_id
),
-- A family is every column that shares a key, whether or not it already has a
-- group. Counting only the ungrouped ones would mean a column arriving after
-- its family already has a group looks like a family of one and never joins:
-- insert exam-1 and exam-2, they form "Exam", then exam-3 arrives alone and is
-- left out. Sizing and titling over the whole family also keeps the title
-- stable, so a late arrival resolves to the group that already exists rather
-- than minting a near-duplicate.
family as (
  select
    c.gradebook_id,
    c.class_id,
    c.group_key,
    count(*) as family_size,
    min(c.name) as name_lo,
    max(c.name) as name_hi,
    min(c.sort_order) as first_sort
  from cols c
  group by c.gradebook_id, c.class_id, c.group_key
),
-- Only ungrouped columns are assigned; the rest are here for sizing only.
eligible as (
  select c.*
  from cols c
  join family f
    on f.gradebook_id = c.gradebook_id and f.group_key = c.group_key
  where c.group_id is null
    and f.family_size >= 2
),
agg as (
  select f.gradebook_id, f.class_id, f.group_key, f.name_lo, f.name_hi, f.first_sort
  from family f
  where f.family_size >= 2
    and exists (select 1 from eligible e
                where e.gradebook_id = f.gradebook_id and e.group_key = f.group_key)
),
common as (
  select
    a.*,
    substr(
      a.name_lo,
      1,
      coalesce(
        (
          select min(i) - 1
          from generate_series(1, least(length(a.name_lo), length(a.name_hi))) as g(i)
          where substr(a.name_lo, i, 1) <> substr(a.name_hi, i, 1)
        ),
        least(length(a.name_lo), length(a.name_hi))
      )
    ) as name_prefix
  from agg a
),
titled as (
  select
    c.gradebook_id,
    c.class_id,
    c.group_key,
    c.first_sort,
    coalesce(
      nullif(btrim(regexp_replace(c.name_prefix, '[^A-Za-z]+$', '')), ''),
      initcap(replace(split_part(c.group_key, ':', 2), '-', ' '))
    ) as title
  from common c
),
-- A title collision inside one gradebook would trip the uniqueness constraint,
-- so disambiguate deterministically rather than failing the migration.
deduped as (
  select
    t.*,
    row_number() over (
      partition by t.gradebook_id, lower(t.title)
      order by t.first_sort, t.group_key
    ) as title_rank
  from titled t
),
titles as (
  select
    d.gradebook_id,
    d.class_id,
    d.group_key,
    d.first_sort,
    case when d.title_rank = 1 then d.title
         else d.title || ' (' || d.title_rank || ')' end as title
  from deduped d
),
-- Existing groups keep their positions; anything created here is appended after
-- the current high-water mark, so re-running cannot renumber a group an
-- instructor has already placed.
high_water as (
  select g.gradebook_id, max(g.sort_order) as max_sort
  from public.gradebook_column_groups g
  group by g.gradebook_id
),
plan as (
  select
    t.gradebook_id,
    t.class_id,
    t.group_key,
    t.title,
    -- A title of only punctuation would slugify to '', which the slug_format
    -- check rejects. Fall back to the family key, unique per gradebook.
    coalesce(
      nullif(
        regexp_replace(
          regexp_replace(lower(t.title), '[^a-z0-9]+', '-', 'g'),
          '^-+|-+$', '', 'g'
        ),
        ''
      ),
      regexp_replace(
        regexp_replace(lower(replace(t.group_key, ':', '-')), '[^a-z0-9]+', '-', 'g'),
        '^-+|-+$', '', 'g'
      )
    ) as slug,
    (
      coalesce(h.max_sort, -1)
      + dense_rank() over (partition by t.gradebook_id order by t.first_sort, t.group_key)
    )::integer as sort_order
  from titles t
  left join high_water h on h.gradebook_id = t.gradebook_id
),
-- DO NOTHING rather than DO UPDATE: if a group with this slug already exists,
-- it is the instructor's, and its name and position are not ours to overwrite.
-- The columns still get attached to it via `resolved` below.
inserted as (
  insert into public.gradebook_column_groups (class_id, gradebook_id, name, slug, sort_order)
  select p.class_id, p.gradebook_id, p.title, p.slug, p.sort_order
  from plan p
  on conflict (gradebook_id, slug) do nothing
  returning id, gradebook_id, slug
),
resolved as (
  select
    p.gradebook_id,
    p.group_key,
    coalesce(i.id, g.id) as group_id
  from plan p
  left join inserted i
    on i.gradebook_id = p.gradebook_id and i.slug = p.slug
  left join public.gradebook_column_groups g
    on g.gradebook_id = p.gradebook_id and g.slug = p.slug
)
update public.gradebook_columns gc
set group_id = r.group_id
from cols c
join resolved r
  on r.gradebook_id = c.gradebook_id
 and r.group_key = c.group_key
where gc.id = c.id
  and r.group_id is not null;

  get diagnostics v_assigned = row_count;
  return v_assigned;
end;
$function$;

comment on function public.backfill_gradebook_column_groups(bigint) is
  'Classifies ungrouped gradebook_columns into gradebook_column_groups by slug family, ignoring sort_order holes and titling each group from the common prefix of its members'' names. Idempotent: only touches columns whose group_id is NULL, and never renames or moves a group that already exists. Returns the number of columns assigned.';

grant execute on function public.backfill_gradebook_column_groups(bigint) to authenticated;
grant execute on function public.backfill_gradebook_column_groups(bigint) to service_role;

-- Run it once for every gradebook that exists as of this migration.
select public.backfill_gradebook_column_groups();
